# Generated by Django 2.2.16 on 2022-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220721_1505'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_rev',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_review'),
        ),
    ]
